services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: xafragsql-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Dev_Spike_Pw_2025!"
      MSSQL_PID: Developer
    ports:
      - "14333:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
