// <auto-generated />
using Microsoft.Data.SqlTypes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XafRag.Module.BusinessObjects;

#nullable disable

namespace XafRag.Module.Migrations
{
    [DbContext(typeof(RagDbContext))]
    [Migration("20260920175520_InitialRagSchema")]
    partial class InitialRagSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XafRag.Module.BusinessObjects.KnowledgeChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    b.Property<SqlVector<float>?>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<int?>("KnowledgeArticleId")
                        .HasColumnType("int")
                        .HasColumnName("knowledge_article_id");

                    b.Property<int>("SourceType")
                        .HasColumnType("int")
                        .HasColumnName("source_type");

                    b.Property<int>("TokenCount")
                        .HasColumnType("int")
                        .HasColumnName("token_count");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("KnowledgeArticleId");

                    b.ToTable("knowledge_chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
